CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(1000) NOT NULL,
	RECOMMENDER_ID VARCHAR2(1000)
);

SELECT * FROM TBL_MEMBER;

INSERT INTO SCOTT.TBL_MEMBER
(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, 'hds1234', '1234', '한동석', '경기도 남양주시');

