CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	POST_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID),
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

SELECT * FROM TBL_REPLY;

CREATE SEQUENCE SEQ_REPLY;

SELECT * FROM TBL_POST;

INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 2);
INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 2);

INSERT INTO TBL_REPLY 
VALUES(SEQ_REPLY.NEXTVAL, '댓글 테스트1', 21, 2);
INSERT INTO TBL_REPLY 
VALUES(SEQ_REPLY.NEXTVAL, '댓글 테스트2', 21, 2);
INSERT INTO TBL_REPLY 
VALUES(SEQ_REPLY.NEXTVAL, '댓글 테스트3', 22, 2);



SELECT P.*, M.MEMBER_ID, M.MEMBER_NAME, NVL(REPLY_COUNT, 0) REPLY_COUNT FROM TBL_POST P 
LEFT OUTER JOIN
(
	SELECT POST_ID, COUNT(ID) REPLY_COUNT FROM TBL_REPLY 
	GROUP BY POST_ID 
) R
ON P.ID = R.POST_ID
JOIN TBL_MEMBER M 
ON P.MEMBER_ID = M.ID;